import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import React from 'react';
import Sidebar from './components/sidebar/Sidebar';
import './globals.css';
import { Providers } from './providers';
import { TwoColumnsLayout } from './templates/TwoColumns/TwoColumns';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <Providers>
          <div className="text-foreground bg-background min-h-screen w-full">
            <TwoColumnsLayout
              firstColumn={<Sidebar />}
              secondColumn={<main>{children}</main>}
            />
          </div>
        </Providers>
      </body>
    </html>
  );
}
